#!/usr/bin/env bash
# 01-crew: bash completion for crew command

function _crew () {
  local CREW_PACKAGES_PATH="${CREW_PREFIX}/lib/crew/packages/"
  local CREW_LOCAL_REPO_ROOT="$(git rev-parse --show-toplevel 2> /dev/null)"
  if [[ -z "$CREW_LOCAL_REPO_ROOT" ]]; then
    local CREW_LOCAL_REPO_ROOT_PACKAGES_PATH="${CREW_PACKAGES_PATH}"
  else
    local CREW_LOCAL_REPO_ROOT_PACKAGES_PATH="${CREW_LOCAL_REPO_ROOT}/packages/"
  fi

  # available options
  local avail_opts_short=(-b -t -c -d -k -L -s -S -v -V -h)
  local avail_opts_long=(
    --include-build-deps
    --tree
    --color
    --no-color
    --keep
    --license
    --build-from-source
    --recursive-build
    --verbose
    --version
    --help
  )

  # available commands
  local cmds=(
    build
    const
    deps
    download
    files
    help
    install
    list
    postinstall
    prop
    reinstall
    remove
    search
    sysinfo
    test
    update
    upgrade
    upload
    whatprovides
  )

  # parameter that trigger this function
  local current="${COMP_WORDS[COMP_CWORD]}"

  if [[ "${current:0:1}" == '-' ]]; then
    # match ${current} with available option list if ${current} start with '-'
    # save result to $COMPREPLY variable
    COMPREPLY=( $(compgen -W "${avail_opts_short[*]} ${avail_opts_long[*]}" -- "${current}") )
  elif [[ ${COMP_CWORD} == 1 ]]; then
    # match ${current} with command list if ${current} is the first argument
    COMPREPLY=( $(compgen -W "${cmds[*]}" -- "${current}") )
  else
    # match ${current} with available packages
    local matched_pkgs=( ${CREW_PACKAGES_PATH}/${current}*.rb )
    local local_repo_root_matched_pkgs=( ${CREW_LOCAL_REPO_ROOT_PACKAGES_PATH}/${current}*.rb )

    if [[ ${#matched_pkgs[@]} > 1 || ${#local_repo_root_matched_pkgs[@]} > 1 ]]; then
      # use basename to remove extension and path
      COMPREPLY=( $(echo "$(basename -s .rb ${matched_pkgs[@]}) $(basename -s .rb ${local_repo_root_matched_pkgs[@]})") )
    else
      return 1
    fi
  fi
}

# register this function as completion function for crew command
complete -F _crew crew

